// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import (
	runeentity "antia/internal/entities/runeentity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RuneStore is an autogenerated mock type for the RuneStore type
type RuneStore struct {
	mock.Mock
}

// GetRunes provides a mock function with given fields: ctx
func (_m *RuneStore) GetRunes(ctx context.Context) ([]*runeentity.Rune, error) {
	ret := _m.Called(ctx)

	var r0 []*runeentity.Rune
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*runeentity.Rune, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*runeentity.Rune); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*runeentity.Rune)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRuneStore creates a new instance of RuneStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuneStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuneStore {
	mock := &RuneStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
