name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  # Check if there any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: pre-commit/action@v3
